### ISSUE TITLE
[bug] conflicts with HUD and Active Auras

### ISSUE THREAD

**Issue by rinnocenti** [theripper93/Levels#11]
I'm trying to find ways to replicate and isolate the problem.
however some conflicts are occurring, using the Token HUD and Active Auras.

(the error only appears when I activate the "levels" module)
When a token that has an aura is placed on the map (without any level).
when I try to roll a massive initiative, it causes an error.
![image](https://user-images.githubusercontent.com/3178127/121821436-4c642600-cc6f-11eb-8491-0f0c99b89350.png)

from there, if I can no longer roll the initiative for this character.
and also if I remove or try to add another token on the screen, the levels module doesn't allow it and I need to update the scene.
![image](https://user-images.githubusercontent.com/3178127/121821465-9d741a00-cc6f-11eb-900c-889dba64d40e.png)
I haven't tried to isolate all the factors yet to make it easy to replicate, but I'm running tests to isolate them.

**Comment by theripper93** [comment]
so, what i can say is that the error you are getting from levels (the lib wrapper one) is no actually related to levels at all. it's just that i'm replacing a foundry founction and it happens to trigger that error, it seems the error is caused by the fact that the token somhow has no image. Try to isolate the conflict and let me know, i'm assuming it doesn't happen if AA\Token HUD are disabled

**Comment by theripper93** [comment]
it seems you are using plutonium, try without that and check if the issue persists
