### ISSUE TITLE
Change or Addition to Stair functionality.

### ISSUE THREAD

**Issue by Iankid** [theripper93/Levels#26]
I was hoping for a function for stairs to have a one way change. To the effect that stepping on the "stair" polygon will change the character to another elevation, but not change back if stepped on again.

I essentially want to create "steps" that a player may go up or down, without having to worry about if they can easily turn to go back the other way, part way.

The major use for this, is to help confirm correct elevation at the "top" and "bottom" of the change. so that a token that stepped on from 0 to 10 lets say, but doesn't continue up and leave the zone, and instead turns back down, does not then have an elevation of "10" when they should have "0"

**Comment by theripper93** [comment]
jsut use the elevator functionality

**Comment by tristanvann** [comment]
Is there a way to turn off the dialog for elevator and just have it automatically work like stairs? Because otherwise it doesn't really work as a solution to this issue. Expected behavior would be: token moves into the trigger space, module sets elevation for that token to a static number, no dialog box.

**Comment by theripper93** [comment]
Afraid not, i left all the more advanced elevation setting options to monk's active tiles since it does a great job at it. There is also a video on it somewhere

**Comment by tristanvann** [comment]
Monk's Active Tiles was exactly what I needed. Thanks!
