### ISSUE TITLE
Tile not disappearing with vision or token superposition in "Bridge" scenario

### ISSUE THREAD

**Issue by yorkshirelandscape** [theripper93/Levels#9]
I'm somewhat hesitant to post this one, as I had it working at one point. But it doesn't seem to work now and I've checked everything I can think of.

Foundry ver. 0.8.6
Levels ver. 0.5
Pathfinder 2e ver. 2.1.1.6052
Chrome ver. 91.0.4472.77

So, step 1... build a bridge. Something like this:

![image](https://user-images.githubusercontent.com/1088016/121783154-22313c00-cb7b-11eb-94fd-29d5e3cff9f4.png)

The bridge tile is at height 0 and is set as overhead, mask, and fade. The walls extend from 0 to -infinity. 

![image](https://user-images.githubusercontent.com/1088016/121783291-b7343500-cb7b-11eb-98ca-f5004b881add.png)

When you move your token to -10 feet and either look or walk under the bridge, the tile doesn't disappear as it should. I do seem to recall reading something about needing to create complete walls for the "building" for vision to work properly, but I've tried it with and without. No difference.

**Comment by theripper93** [comment]
i would like to check this out on discord, pm me when you have the time to share as i haven't tested with negative stuff

**Comment by Koalahund** [comment]
Works for me.

0ft vision:
![a3cae864239189da65fd8a5f2e1a40e3](https://user-images.githubusercontent.com/85458282/121791319-fea4da80-cbe8-11eb-9795-ee47d2acb56e.png)

-5ft vision:
![6b947dd999321c9a3b990f416ab936df](https://user-images.githubusercontent.com/85458282/121791327-10867d80-cbe9-11eb-82a4-5623066ad1f3.png)


make sure to close the walls to define a building like in this screen:
![5aa987fbe0cdb775fbfe04a8022b3437](https://user-images.githubusercontent.com/85458282/121791341-2a27c500-cbe9-11eb-9ed0-bc42b4f0c6da.png)

AND
you have to place a wall around your whole scene so the mask(coutout tile on vision) setting works

also make sure to set the occlusion mode to none(always visible) or the left and right side of the bridge will fade when moving under the middle part of the bridge(that is cut out due to mask(cutout tile on vision) setting).

tile settings:
![2b8197373a024ae89665d4e0beb6d1a0](https://user-images.githubusercontent.com/85458282/121791399-c94cbc80-cbe9-11eb-8313-7e68e029e0e6.png)

wall settings:
![752cc35b570036690e893db41dbcac01](https://user-images.githubusercontent.com/85458282/121791402-ca7de980-cbe9-11eb-9c29-5f523a749ff1.png)

**Comment by theripper93** [comment]
should be fixed in 0.5.3\4
